datasets:
  - class_name: DebugDataset
    class_args:
      num_examples: 100
    data_name: debug
    data_sampling_ratio: 1
    max_input_tokens: 4096
    max_output_tokens: 4096

load_args:
  load_path: checkpoints
  iteration: 4000

generation_parameters:
  batch_size: 8
  do_sample: false
  max_new_tokens: 100

output_dir: outputs
